In [40]:
import numpy as np

In [29]:
# Creating arrays from lists
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("1D Array:", arr_1d)

print("----")

print("2D Array:")
print(arr_2d)

1D Array: [1 2 3 4 5]
----
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
liste = [1, 2, 3, 4]

resultat = liste *2
print(resultat)
#to do the right math operation, we need to loop

print("----")

arr_1d = arr_1d *2
print(arr_1d)

[1, 2, 3, 4, 1, 2, 3, 4]
----
[ 2  4  6  8 10]


In [30]:
print("\n=== Array Properties ===")
print("Shape:", arr_2d.shape)
print("Dimensions:", arr_2d.ndim)
print("Data type:", arr_2d.dtype)


=== Array Properties ===
Shape: (3, 3)
Dimensions: 2
Data type: int64


In [38]:
print("\n=== Special Arrays ===")
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
range_arr = np.arange(0, 10, 2)  # Like range() but returns array
random_arr = np.random.random((2, 2))

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Range array:", range_arr)
print("Random array:\n", random_arr)


=== Special Arrays ===
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Range array: [0 2 4 6 8]
Random array:
 [[0.71908335 0.8729322 ]
 [0.82888687 0.37636522]]


In [39]:
print("\n=== Array Operations ===")
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("a + b =", a + b)           # Element-wise addition
print("a * 2 =", a * 2)           # Broadcasting
print("a * b =", a * b)           # Element-wise multiplication
print("np.dot(a, b) =", np.dot(a, b))  # Dot product


=== Array Operations ===
a + b = [ 6  8 10 12]
a * 2 = [2 4 6 8]
a * b = [ 5 12 21 32]
np.dot(a, b) = 70


In [42]:
print("\n=== Useful Methods ===")
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Sum:", data.sum())
print("Mean:", data.mean())
print("Max:", data.max())
print("Reshaped to 2x5:\n", data.reshape(2, 5))


=== Useful Methods ===
Sum: 55
Mean: 5.5
Max: 10
Reshaped to 2x5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
